local M = {

	["michael"] = {
		[[MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxolc:::okKNWMMMMMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl;'........';cokKWMMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMMMMKl..   .............'oKMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMMMXc.  ...............  .cXMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMMWx. .;looooollc:;;;,.....oXMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMMK: .'ck00KKKKKK00Okxoc;,..dWMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMMO'  .ck0KKKKKXXKKK0Okdl;..cXMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMNO:..lk00KKKKXXXKK00Okdl;..dWMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMWK0kclOOkxxdxxkOKKK0Okxdl,.cKMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMWK0OxxO00kdooodk0Oxoccll:';0MMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMWX00kkOKKKK000000xlolc::;'cKMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMWN0kOO0KKXXKKK00dldkxdo::kWMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMMW0kO00KKXK00000dcdkkdl:dXMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMMWX0kO00KKKK0OOkdlldxdookXMMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMMMXdx0kkO0000OOOOxolodoldXMMMMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMMMMMNOc'c0KOkOO00OOkkdolooldKWMMMMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMMMMWNKxc'..'oXNX0OO000OOxollco0NWMMMMMMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMMMMMWXOo:'......'lKWWXKOkxddoc::'.';cx0XWWMMMMMMMMMMMMMMMMMMM]],
		[[MMMMMMMMMNKkoc,............:OWMWNKxoc:ldl'... ..,:lodkOKXWMMMMMMMMMMMM]],
		[[MMMMMWXOo:'.................;OWMWNOdc;ldl.............'';cdXMMMMMMMMMM]],
		[[MMWXkl,......................;kNXk:''..:l,.................lNMMMMMMMMM]],
		[[MNd,..........................,d0Oc.'''okc.................;0MMMMMMMMM]],
		[[Wd.............................,d0o,'.'o0o'.................oXMMMMMMMM]],
		[[Xc..............................,ol,'..cOx'.................,OWMMMMMMM]],
		[[K:...............................,;;'.',dx,..................cKMMMMMMM]],
		[[K:................................';'...;o;...................dWMMMMMM]],
		[[Nl..................................'...':;...................:KMMMMMM]],
		[[No.......................................,,........... ........oNMMMMM]],
		[[Wo.............   ...................................   .......'kWMMMM]],
		[[Nl.............   ..................................     .......;OWMMM]],
		[[Nc.............   ...............   ...............      ........;OWMM]],
		[[Xc..............  ................   .............      ..........;0MM]],
		[[Xc..............   ...............    .. .......      .,,;;'.......:KM]],
		[[Xc...............  ................      .....      .:dkkkx:........cK]],
		[[Nl................ ............. ...     ....     .,okOOkkkl........'x]],
		[[Wd.................  ......      ...     .       .;odooc::,..........l]],
		[[MO,...............  ..;ccc::;'.......   .        .''.................c]],
		[[MXc..................,okkkkkkxdoollc;....'.    ......................']],
		[[MWx..................'cxkO000OOOOOOOx:'.,lc...........................]],
		[[MM0,................ ...;ok0000000000d,.'lOo.........................c]],
		[[MMXc................     .,cdkOOOO0Okc..'dK0c.......................;O]],
		[[MMWk'.............  ....    .';::;,,,,'.'cdxo'..................':oOXW]],
		[[MMMNd...................            ....  ..................':dOXWMMMM]],
		[[MMMMK;...................           ..     ...............;oONMMMMMMMM]],
	},

	["prison_mike"] = {

		[[;;;;;;;;;;;;::::;::::;;:;;,,:odc;;;;;::::;::::c:ccc:cccccllcolcllcldxo:;;;;;;;;;;;;;;;;;;;;;;;;]],
		[[;;;;;;;;;;:::::::::::::::;;;;ldl:;;;::codool:::::::clcodoxxoxdddlcccc:::;;;;;;;;;;;;;;;;;;;,,,;]],
		[[;;;;;;;;::::::::::::::::::::cooc:;;;;coooodl::::::ccododoooooodddolc::::;;;;;;;;;;;;;;;;;;;;;;;]],
		[[;;;;;:::::::::::::::::::::clooc;;;;;;clldo::::::::looollooodooooooolc::c:;;;;;;;;;;;;;;;;;;;;;;]],
		[[;;;::::::::::::::::::::::clc:;::;;;;;;;:::;;:::::cooollloolddoooollll::ll:;::;;;;;;;;;;;;;;;;;;]],
		[[;;::::::::::::::::::::::::::,;lol:;;;;;;;;:;;::::coolccclc:llldxoolclc;clc::;;:;;;;;;;;;;;;;;;;]],
		[[:::::::::::::::::::::::::::;,:ccoc;;;;::lc::;;::codoccloolclcc:c::ccll:;:c:;;;;;;;;;;;;;;;;;;;;]],
		[[:::::::::::cc::::::cc::::::,',lo:,,,:ooldl:::clloodxxxxkxxxkkxdoollcc:;,;;;;;;;;;;;;;;;;;;;;;;;]],
		[[:::::::cccccccc::cccccccc::,',;;,,,',ccllc:::;;;;;;:loxkkkkxl:;,,,;:c:,.',;:;;;;:;;;;;;;;;;;;;;]],
		[[::::::cc:cccccccccccccccc::;,,'...,:ldxxool:,,'''',;:codxxdl;,'...',:cc'..;::;:;::::::;;;;;;;;;]],
		[[::::::cccc:cccccccccccccccc,..  .:dxkkxdl:,,,;;;,.',;:ldxd:,'...','';lo:..,::::::::::::::::::::]],
		[[::::cccccccccccccccccccclddl,. .,lxkxxdo:;:cl;,clc;;;cdO0x:'','';c:,,:ol.'lol::::::::::::::::::]],
		[[::::cccccccccccccccccccllc::::,.'oxxkkxddxxdoccloolloxOKX0d:::;,;lolcldo;'::cc:::::::::::::::::]],
		[[:::cccccccccccccccccccclc;ldlol,;dxxkOOOOOOxdooooodkO00KXKOdolcccloddxxdc,,,;c:::::::::::::::::]],
		[[:ccccccccccccccccccccccldxkxclkxodxxkO0000OOkxddxk000000XX0kxxooodxxkkkdllcccc:::::::::::::::::]],
		[[ccccccccccccccccccccccclxOkdlx0OxdxxxxkkOOOOOOO00OkO0000XXKOkkkkxxxkOkxdooolc::::::::::::::::::]],
		[[ccccccccccccccccccccccccdOOOOOOkxddxxdddxxxxkOOkdcoO0000000OOxodkkxxxdddddolc::::::::::::::::::]],
		[[cccccccccccccccccccccccclxOKK0Okxdddddddooddxkdc:cloclooollloo::ldxdooodxxocc::c:::::::::::::::]],
		[[cccccccccccclllccccccccccllodddxxdddddddddddxdlcoxxl;,;;,'',;cc:cldoooodxxl:cc:cc::::::::::::::]],
		[[cccccccccccccccccccccllccc:;:cldddddddddddxxxxdxkOkxo:,...,:looollooooolllc::c:::::::::::::::::]],
		[[cccccccccccccccccclllllllllc:clddoddooddxxxxkkkkkxdoll:,,;:cllodoooooolccccccccc:cccccccc:cc:::]],
		[[ccclcccccccccllcccllllllll:.,ooooooooooddxxkkkxolcllodolcclc:;:looooollcccccccccccccccccccccc::]],
		[[ccccccclccccllllllllllllc;'.;Okolcclllloodxxxdolodxdolc:::cllc::clolllcccccccccccccccccccccccc:]],
		[[ccllllllclllllllllllllc:,...'kXxc::::ccclooooodxxoc:,,,,,''';clc:clcccccccccccccccccccccccccccc]],
		[[cllllllccllllllllllc:;'......:0Xkl:;;;;:ccccllol:;;:clcccc:;,;cc::::cccclcccccccccccccccccccccc]],
		[[ccllcclcllllllllc:;,'.........lXN0dc;,;;::ccccccccooollcccccc::c:;:clllclcccccccccccccccccccccc]],
		[[ccllllllllllc:;,'..............lXWXOdc:;;;;;::coooolc::::;;clc::::clllccccccccccccccccccccccccc]],
		[[ccllllllc:;,'...................lXWNKkoc;,,,,;;:c::;,,,,,'',;:::cclllllcccccccccccccccccccccccc]],
		[[cccc:;;,'........................lXWNXOdl:;'''',''......''',ldlclllllllcllllccccccccccccccccccc]],
		[[,,''..............................oXNWN0xc:;,'..''...'',;;:dKd;:cllllllllllllccccccclcccccccccc]],
		[[..................................'dXNNNKkl;;;;,'....,;;:lkXXl..';:cllllcllllcccccccccccccccccc]],
		[[...................................,kNNNNXOo:;;;;,'',,;lx0XNKc.....',;::cllllllcccllllllllccccc]],
		[[....................................:0WNNXX0xl:;;:cc::cclkXNXl..........',;::cllllclllllllllccc]],
		[[.....................................lXWNNXKKOkdol:''''..;dXNl...............',:clllllllllllllc]],
	},

	["michael_smirk"] = {

		[[0000000000Oo.....     ........',;loddkOOOOkkkdc;''''','............',:kXXXXXXXXXX]],
		[[llllllllccc,...........'',;:cclodkOO0KKKK000Okxl:,,'''......     ..',,:xKXXXXXXNN]],
		[[ooolllllllc'. ....';:cllloodxxkOO0000000KKKK0Okxl;,,,'.......      .''':x00000KXX]],
		[[0000000000k;  .,:lodxxxxxxxxxxxkkkOOOOO0KKKKK0Oko:,',.........     .....cxxxxxxkk]],
		[[KOkxkkkkxxd; .;odxkkkkkkxkkxxxxxkkkkkkO00KKK0OOkdl,.........''..  .. ...l00000000]],
		[[0dccooooooo;.'ldxxxxxxxdddddddxxxxkkkkOO00000Okxdl:'.   .....''......  .o0OO00000]],
		[[0ocoOKKKKK0o',oxxkkkxxxdddxxxxxxxxxxxkkO00O000Oxdl:,.     .........,,. 'xK000KK0K]],
		[[0ocd0XXXKKKk:;dxkkkOkkkxxxxxxxxkkkkOO0OOO00000Okxoc;.          ....','.;k000000KK]],
		[[0ocd0XXXKKXKocxkkkOOkkOOkxkOOxdddddddxkkOOOOOOOOkxo:'.          ....',;lkOOOOOO0K]],
		[[0ocd0XXXXXKKOolc::lxxxkkxddoc;,''''';;:ldkOO00OOOOxoc;.        .,ldxdc:lO0O00O000]],
		[[0ocd0XXXXKKKx;'....;coxkxoc:,''.....',;:lodxOK0OOOOkxdc'.    ..,clccoxooO000OO000]],
		[[0dcd0XXKKKKKOo;'''...;oddl:;,''....,;::;;:cldxOOOOOO0Oxc,.. .;lllddc:lxO00OOOO000]],
		[[0dlx0XXXXXKKKkc''..''':oolc:;,'.....,:::;:::lodkOOO000kl;...;xxoxOOkddk0000000000]],
		[[0dld0KKKKKKK00xolc:cc:lkkxolcc:,,;,,cooodxxxkkkkO00000ko:''lkKkccoxOkxO00000000O0]],
		[[0dlx0KKKKKKKKKOxxolc:oO0OOkdodolc:cclodxxkOOOOO0000OOOkxddk0XXKkddoxOOkO000000000]],
		[[0dld0000000KKKkdxxdoxO0KK00OkkkxxdooodxkO0000KKKK0OOOkkxkkO0KK0kOOkkOkk0000000000]],
		[[0dclodddddddxxxxk000KXKKKOOOOkddkOO000KKKXXXXK0000OOOkkkkOOOOO0KNXKKkdOKK000000KK]],
		[[KOxxxxxddxxddxxkxxdkKXKK0O00K0xlcldkOOO00KKKK0OOkOOOOkkkOOOOOO0XXXKkco0K0000OO00K]],
		[[XKKKKKKKKKKK00Oxollk0OOO00Okxxollc::coddxkkkOOOkkkkOOOOOOOOOkkOOxdc,:xKK00000000K]],
		[[NNNNNNNNXXXXXX0dc::ooooooc:,,;:loll:;;ccllooddxxkkkOO00OOOOOxoo;...:xOO0OOO000000]],
		[[WWWWNNNNNNNNNNKdcc;,;;;:,'',:clollcc:;,;ccccclodxxkkkkOOOkOkddo'.'oOKKKKKKKKKXXNN]],
		[[OOOOOOOOOOOkkkkocc,.,:c:,'',:cllclc:::;,,clllccloddxxxxkkxxxdxdllxOOOOOOOOOO0000K]],
		[[xxxxxxxxxxxxxxxdcc;..',cl:;::cc:cc:;;,'..,;cllc:clooooodddddxkOKKKKK0K00000000000]],
		[[ddolooooodddddddlc:;,;:okxdodddxxxolc;'',;;;cll:::cc:cccllodxO0XWKOKKKKKKKKKKKKKK]],
		[[cc:;,,'...,;;;;;;;cc:ldxkOkkOkkkkxdolccclc:::ll:;::::;;;:cldOO0NWKod0KKKKKKKKKKKK]],
		[[..                'coxxxxxdoddooooooollllllc:cc:;:::;;;;:lox0KNMMWk:lk00000KKKKKK]],
		[[                   .cdxxxxxdddddddddooddoollc:;;;::;;;:cldxkKWMMMM0l:cok00KKKKKKK]],
		[[...                 .cxxxxxxxddddddddddoollc:;;;;;,,;:ccldOXWMMMMM0c;::cdO000KK0K]],
		[[..                   .ldxdddoooddddddooolcc:;;;;,,,;:::cd0NWMMMMMNx;;;;:::lllclcc]],
		[[                      'lollcccccloooolcc:;;;;;;,,;;;::oOXWWMMMMMWO:,,,;;:::::::;;]],
		[[.                      .,,,,,;;;::::;;,,,,,,,,,,,,;:oOXWWWMMMMMW0c,,,;;;;;;:::;,;]],
		[[                         .;oc;,''''.''''',,,''..':d0XNWWMMMMMMMKl',,;,;;;;;;;;,'']],
		[[                         .oXK0xl:'......''''..,cxKNNWWWMMMMMMMXo'',,,,,;;;;;,,,'.]],
		[[ ..,:c::;;,'''''',,,,.....lXNXK0ko:'.....'',:dOXNNWWWWMMMMMMMNd,',,,,,;;;;;,,,,'.]],
	},

	["dwight"] = {
		[[kkkkOO0KKKKKOdllcc:,'..........',,,,,'..';::;;,,,,;:ccldxkkOOOOOOOO0OO]],
		[[kkxkkO0000Okdl;',,'........'',,,,,,;;;cc:;;::::;,,'',;;:lxkkOOOOOOO0OO]],
		[[kkxxxxxdollc;...'.. ..........''',,;coxkdc;,,'',,,''...',lkOOOOOOOO00O]],
		[[kkxxxxxdlc:,''..... .......'',;:llodxkOOkdlc,............,okOOOOOO000O]],
		[[kkkkkkxxo:'''...........',::coxkOO000000Okxdl:,..   ......,oOOOOOO000O]],
		[[kxkkkkkxc....  .......'';;:lxOKXXXXXXKKK0OOkxdoc,..........;kOOOOO0000]],
		[[kxkkkkkx;..     ..'..'',:cccok0XXXXXXKKK000Okxxdl,.. ......'dOOOOO0000]],
		[[kxkkkkkx;.      ....,,'',codddk0KXKKKKK000OOkkxdo:.   .....'oOOOOO0000]],
		[[xxkkkkkd,       ...'clc;;cokOOO0000000000OOOkkxdol;..  .....ckOOO00000]],
		[[xxxkkkkd'        .'cdxkxddxO0K000000000OOOOOkkxdddoc;'.  . .;xOOOO0000]],
		[[xxxkkkkd,        .:dkOOOOOO0KKKKK0000OOOOOOOkkkxxxddoc;..   'dOOO00000]],
		[[xxxkkkkd,      ..,lxkkOO0000KKKK000000OOO000OOOkkxddolc,..  .dOOO00000]],
		[[xxxkkkxd:.    ..'cdxkkkOOOOOOOOOOOOOO00000OOOkkkxxddoll;.. .;xOOO00000]],
		[[xxxkkkkxd,.  ...'lxxxxxddooolclooddddxxxkxxddddolllclll:...'dOOOO00000]],
		[[xxxkkkkkkoc:,.  .;lodollc:;,''''',;:ccloocc:::;,,;;::clc..,okOOOO00000]],
		[[kxxxkkkkxl;co:..collool:::;'.,:,'''',clol:;''....,;,:cl:''lxxkkOOO0000]],
		[[Okxxkkkkxl;clc,,okkkkkxxxxdlcllc::;,:lxkdc:::;,,;cc:ccc:;lxxxxxkkO0000]],
		[[Okkxkkkkkxool;':dkkOOOOOOkxddooodxdolxKKOo:llccllllllllc;lxxxxxxkO0000]],
		[[Okkxxkkkkkxdl;;cdkkkOOOOOkkkxkkOOkxdx0K0Oxllddoooooooool:cddxxxxkO0000]],
		[[Okkxkkkkkkkxkxc:lxxkkkkkkkkkkOOkdodxxkOOkxolodddodoooool:ldxxxxxkOO00O]],
		[[xddxxxxkkkkkkkl,:oxxkkkOOOOkkkxdlloc,,clc:clodddddoooooc;coxkkxxkOO00O]],
		[[llodxxxxxxxxkko::odxxxkkkkkkxxxkkxxdolccc:clodddddooool;';ldxxdxxkOOOO]],
		[[cccllllc::::cclldddddxxxxkkxkkO00KK0KOddxdoooooooooollc:;;;cllodxkOOOO]],
		[[;,''..........,cddddddddxxxxkOO0OOkxdooooloooooooooolloo:'..',coxkOOOO]],
		[[...           .:loddddddxkkxdoolllcc:::;;,;:clloooollllc;....':oxkOOOO]],
		[[              .:lllooddxxkxddooollllccccccccclooooollcc;'....,coxkOOOO]],
		[[             .,lolclloddddddxxxdddolc:;:ccllllloooll;''......,:oxkOOOO]],
		[[             .cddoccclloooddxxkO000Okxdddoooollllllc;,,'''.'',coxkkOkk]],
		[[            .;oxxdlccccclllodxxxkkxxxddddooollllllooollllcccclodxkkkkk]],
		[[           .,lxkkdolcc::::::cclllllllllllcllccccloddddddddddddxxxkkkkk]],
		[[           .:okOxdollcc::;;;;;;;;;;;;:::::::::ccodxxxxxxxxxxxxxxxkkkkk]],
		[[          .,lxK0xdooolllc::;;;;;;;::::::;;;::cllodxdxxxxxxxxxxxxxkkkkk]],
	},

	["stanley"] = {
		[[xxdxxxxxxxo;.   .',;;;::cclllooooooolllcc::;;,,,'''''''.....           .cooooodddddddd]],
		[[xxxxxxxxxxl'   ..,;;;;::cccllllllllllccc:::;;;,,''''''......            .;looooodddddd]],
		[[xxxxxxxxxdl.   .',;;;;;::cccccccccccccc::::;;,,''''''.......             .:lollooooooo]],
		[[xxxxxxxxxxo,   .,,;;;;:::ccccccccccc:::::;;,,,''''...........             'clllllllooo]],
		[[xxxxxxxxxxo,  .',;;;;;::::cccccc:::::::;;;,,''''''..........              .:ccllllllll]],
		[[xxxxxxxxxxd,. .,;;;:::::cccccccccccccc::;;,'''''''..........              .::cccccclll]],
		[[xxxxxxxxxxd:...,;;:::::cccccccccclcccc::;;,,,,''''.........               .:::cccccccc]],
		[[xxxxxxddxxdc..';;;;:::::::::::::ccc::::::;;,,''''''........               .;::cccccccc]],
		[[xxxxxxxdxxdc..','''.''''',,,,,,;:;;;:;;;;;,,,,,'''''.......               .;::::cccccc]],
		[[xxddxxxxxxdl,.'.''''''.......',;,'''''''''''''''''..........              .;:::ccccccc]],
		[[xxxxxxxxxxxo;''',,,,,,........,;,'..........................              .;:::ccccccc]],
		[[xxxxxxxxxxxo;''......   .. ..';:;'..........................             .,:::cccccccc]],
		[[xxxxxxxxxxxo;,;,...,'.......';cc;,... ..,'. . ..............             .';:::ccccccc]],
		[[dddddddddddl;;::;,,,'.....',:cll:,'....,c:'.  ..  ..........             .';::ccc:::::]],
		[[ddddddddxddl:;:cc:;,''..';::clol:,'''''''''.................     ...     .,;;:::::::::]],
		[[dddddddddxxo;;:ccc::;;;:::cclooc;;,''',''....................   ......   .,;;;::;:::::]],
		[[ddddxxxdxxxl;,;:::cccclc::clddoc:;,'..';;,,,,,,''''''........  .  ..    .,,;;;;;;;;;;;]],
		[[dddddxxxxxdl;,;;;:cllcc::cloddoc:,''...,::;;;;;,,'''...................';,,,,;;;;;;;;;]],
		[[dddddddddddl;,;;::cc::;::::ccc::,,','..';::;;;,,'.................... .',,,,,,;,,,;;;;]],
		[[dddddddddddo;,;::::::;;'...''''.........';;;;,,,'.................... .',',,,,,,,,,,,;]],
		[[dddddddddddo;,;::::::cc;........   .....',;;;,,''......................''''',,,,,,,,,,]],
		[[ddddddddddxd:,;;;;;:cclc:;;;'''.......'',,,,,,''................''...''''.'''''''',,,,]],
		[[ddddxxdddddd:,,,;;::::cc:cc;'',,''''',,,,,'',,''.....................''''.''''''''''',]],
		[[ddddxdddddddc,,,;;;:;;;,''........'''',,;,,'''''...................  .''.''''''''''''']],
		[[ddddddddddddl,',,;,,'.......''.........'',''..''..................    ...''''''''''''']],
		[[ddddddddddddd:',,'.........'.........  ...'......................       ...''..'....'']],
		[[dddddddddddddo:'....';;::;'..........    ..........  ...........           ..........']],
		[[ddddddddddddddo;....',;cooolcc::;,'...  ........     ........                 .......']],
		[[oolcc:;;,,,''''.........',,,,,,'...     .....      .......                        ....]],
		[['...             .............                    ...                               ..]],
		[[                  ..........  ........          ...                                  .]],
		[[                   ........   ......          ..                                      ]],
		[[                  .cl'.....                ....                                       ]],
	},

	["dundermifflin_logo"] = {

		[[   ;xxxkkkkkkxxdl,.    'dkkkkkl..ckkkkkx:  .okkkko.   ;xkkkx;   .lkkxxkxxkkxdo:'     :kkkkkkkkkkk:  .ldddddddooolc,.         ]],
		[[   dWMMMMMMMMMMMMW0c.  cNMMMMMO..kMMMMMWo  ,KMMMMWd.  oWMMMWl.  '0MMMMMMMMMMMMMNk'  .dMMMMMMMMMMMx. ;XMMMMMMMMMMMMNO,        ]],
		[[   dWMMMMWKk0NMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMMX:  oWMMMWl.  '0MMMMMNOkKWMMMMMx. .dMMMMMMWNXXXo. ;XMMMMMNOkXMMMMMO.       ]],
		[[   dWMMMMNc .OMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMMMO' oWMMMWl.  '0MMMMMO' :XMMMMMx. .dMMMMMMO,....  ;XMMMMMK, lNMMMMX;       ]],
		[[   dWMMMMNc .kMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMMMWd.oWMMMWl.  '0MMMMMO. ;XMMMMMx. .dMMMMMMx.      ;XMMMMM0, cNMMMMN:       ]],
		[[   dWMMMMNc .kMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMMMMXodWMMMWl.  '0MMMMMO. ;XMMMMMx. .dMMMMMMk.      ;XMMMMMK;.dWMMMMX;       ]],
		[[   dWMMMMNc .kMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMMMMMXKWMMMWl.  '0MMMMMO. ;XMMMMMx. .dMMMMMMN000k,  ;XMMMMMWKKWMMWXOc.       ]],
		[[   dWMMMMNc .kMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMMMMMMMMMMMWl.  '0MMMMMO. ;XMMMMMx. .dMMMMMMMMMMNc  ;XMMMMMMWMMMMW0l.        ]],
		[[   dWMMMMNc .kMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMNNMMMMMMMMWl.  '0MMMMMO. ;XMMMMMx. .dMMMMMMXxodl.  ;XMMMMMXocOWMMMWO'       ]],
		[[   dWMMMMNc .kMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMOxXMMMMMMMWl.  '0MMMMMO. ;XMMMMMx. .dMMMMMMx.      ;XMMMMMK, lWMMMMX:       ]],
		[[   dWMMMMNc .kMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMk;dWMMMMMMWl.  '0MMMMMO. ;XMMMMMx. .dMMMMMMx.      ;XMMMMMK, lWMMMMX:       ]],
		[[   dWMMMMNc .OMMMMMK,  cNMMMMMO..kMMMMMWo  ,KMMMMk.'0MMMMMMWl.  '0MMMMMO. :XMMMMMx. .dMMMMMMk'....  ;XMMMMMK, lWMMMMX:       ]],
		[[   dWMMMMWOdONMMMMMK,  :XMMMMMXolKMMMMMWl  ,KMMMMk. cNMMMMMWl.  '0MMMMMXkxKWMMMMMx. .dMMMMMMWXKKKx. ;XMMMMMK, lNMMMMX:       ]],
		[[   dWMMMMMMMMMMMMMWk.  .xWMMMMMWMMMMMMWk.  ,KMMMMk. .xWMMMMWl.  '0MMMMMMMMMMMMMMNl  .dMMMMMMMMMMM0' ;XMMMMM0' cNMMMMX:       ]],
		[[   :OOOO0OOOO00Okd:.    .:x0XNWWWWNX0x:.   'x0000o.  'x0000O:   .dOOOOOOOOOOOOxl,    cOOOOOOOOOOOd. ,k00000d. ;O0000k,       ]],
		[[                           ..',,,,'..       .....      .....         .. ...                  .....     .....    ....         ]],
		[['ooooooooo'   ;oooooooo:.  :dddddd,  .oxxxxxxxxxxd; ,dxxxxxxxxxxxo' ;dxxxxx:      ;ddxddd;  .lkkkkx,   'dkkkkc.'ccccccccccc' ]],
		[[lWMMMMMMMWd. .OMMMMMMMMO. .kMMMMMWl  ;XMMMMMMMMMMWo.cNMMMMMMMMMMMN:.dWMMMMMx.    .dWMMMMWd  .OMMMMMO.  :XMMMMx.,ooooooooooo, ]],
		[[lWMMMMMMMMO. ;XMMMMMMMMO. .kMMMMMWl  ;XMMMMMMWNNNXl.cNMMMMMMNNNNNK;.dWMMMMMx.    .dMMMMMWd  .OMMMMMWo  :XMMMMx..;;;;;;;;;;;. ]],
		[[lWMMMMMMMMX; oWMMMMMMMMO. .kMMMMMWl  ;XMMMMMNo'''.. lNMMMMMKc''''. .dWMMMMMx.    .dMMMMMWd  .OMMMMMMX: :XMMMMx.;dxxkkOOOOkx; ]],
		[[lWMMMMMMMMWo'kMMMMMMMMMO. .kMMMMMWl  ;XMMMMMX;      lNMMMMM0'       dWMMMMMx.    .dMMMMMWd  .OMMMMMMMO':XMMMMx..cldxkOkxdlc. ]],
		[[lWMMMMWWMMMklKMMWWMMMMMO. .kMMMMMWl  ;XMMMMMXc...   lNMMMMMK;....   dWMMMMMx.    .dMMMMMWd  .OMMMMMMMWdoXMMMMx.:kOOOOOkkkkk: ]],
		[[lWMMMMXKWMMXKNMMXKWMMMMO. .kMMMMMWl  ;XMMMMMWXKKKo. lNMMMMMWXKKK0l  dWMMMMMx.    .dMMMMMWd  .OMMMMMMMMNKNMMMMx..;ccccccccc:. ]],
		[[lWMMMMKkKMMMMMMWOOWMMMMO. .kMMMMMWl  ;XMMMMMMMMMMk. lNMMMMMMMMMMWd. dWMMMMMx.    .dMMMMMWd  .OMMMMMMMMMMMMMMMx.'oxxxxxxxxxd, ]],
		[[lWMMMMKoOMMMMMMNoxWMMMMO. .kMMMMMWl  ;XMMMMMW0xxxc. lNMMMMMNOxxxx;  dWMMMMMx.    .dMMMMMWd  .OMMMMNNWMMMMMMMMx,oxl::;;;::lko.]],
		[[lWMMMMK:oWMMMMMK:dWMMMMO. .kMMMMMWl  ;XMMMMMX:      lNMMMMM0'       dWMMMMMx.    .dMMMMMWd  .OMMMMKd0MMMMMMMMx,lkol:. 'clokl.]],
		[[lWMMMMK;:XMMMMMk,dWMMMMO. .kMMMMMWl  ;XMMMMMX;      lNMMMMM0'       dWMMMMMx.    .dMMMMMWd  .OMMMMK;cNMMMMMMMx..cllc. 'lllc. ]],
		[[lWMMMMK,'OMMMMWo.dMMMMMO. .kMMMMMWl  ;XMMMMMX;      lNMMMMM0'       dWMMMMMk...  .dMMMMMWd  .OMMMMK,.xWMMMMMMx. ....         ]],
		[[lWMMMMK,.dWMMMX:.dWMMMMO. .kMMMMMWl  ;XMMMMMX;      lNMMMMM0'       dWMMMMMNK00k,.dMMMMMWd  .OMMMMK, ,KMMMMMMx..d000d.       ]],
		[[lWMMMMK, cNMMM0'.dWMMMMO. .kMMMMMWl  ;XMMMMMX;      lNMMMMM0'       dWMMMMMMMMMN:.dMMMMMWd  .OMMMMK,  lNMMMMMx.'0MMMO.       ]],
		[[:O0000x' .x000o. c00000o. .o000KK0:  'k00000k,      ;O00000d.       c0000000000O,.l0K0000c  .oOOOOd.  .oOOOOOl..xNMMk.       ]],
		[[ .....     ...    .....     ......     .....         ......          ...........   ......                      .lXWO,        ]],
		[[                                                                                                               .ox:.         ]],
		[[.,,'      ..      .,,.     ',,.    .,,.            .,;,.     ..','.      ..   ..   .,,'      ..      .;'  .,.   ,, .,.       ]],
		[[:kxx,    ,xd'     lkkd.   'kxl,    lkxx'          ,l;''.   .:dc,',c:.   'xx,.cOl   ;kxk;    .ok;     :KKo'lk,   ,dxxo.       ]],
		[[:xc,.   ;kkkx,    lx:'    ,xl,.    lkxd.          :o'      .lkc. .co.   ,dclo:ol   ;xl;.   .dkxkc    :OllkK0'    'Ox.        ]],
		[[.'     .:;..;:.   '.      .:;'.    ...,.          .,:;;.    .';:;:;.    .,.   ',   .'      ;:..':'   .:. .cc.    .:,         ]],
		[[                                                                                                                             ]],
	},
}

return M
